### ISSUE TITLE
meet a problem when running the code

### ISSUE THREAD

**Issue by WZheng1999** [xaCheng1996/VFD#2]
Hi,
Thank you for sharing the code.
I have two questions to ask you.
1. I have run your code
```
python train_DF.py --dataroot ./Dataset/Voxceleb2 --dataset_mode Vox_image --model DFD --no_flip --name experiment_name --serial_batches
```
but I meet a mistake as follows:
```
saving the model at the end of epoch 1, iters 0
Traceback (most recent call last):
  File "D:\Learing\VFD-main\train_DF.py", line 139, in <module>
    _auc = auc(real, fake)
  File "D:\Learing\VFD-main\train_DF.py", line 45, in auc
    return roc_auc_score(target_all, label_all)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py", line 545, in roc_auc_score
    y_true = check_array(y_true, ensure_2d=False, dtype=None)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\sklearn\utils\validation.py", line 805, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

```
2. I I didn't find a text file named train_list.txt
```
 parser.add_argument('--image_list', type=str, default='/train_list.txt', help='name of the image_list')
```
I was wondering if you could give me some hints on how to solve both questions

**Comment by xaCheng1996** [comment]
1. This is due to insufficient data - we only provided a few samples in the project. Training on such a small amount of data, the model is easily skewed to one side, causing a list of real or fake to be empty, thus leading to this error.
To get over it, you can expand the data via downloading the full Voxceleb2 dataset or any other visual-audio dataset.

2. This is a redundant parameter (from a very early version); please ignore it. We will clean up these parameters in the next version.
